# This is a basic workflow to help you get started with Actions

name: Simple github actions workflow

# Controls when the workflow will run
on:
  push:
    branches: [ "github_tf" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
        ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
        ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
        ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
        ARM_SUBSCRIPTION_ID: ${{vars.ARM_SUBSCRIPTION_ID}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform
